import pygame

# CONFIGURACION DE PANTALLA
ANCHO_DE_PANTALLA = 1024
ALTO_DE_PANTALLA = 768
FPS = 60

# COLORES (Sistemas de prueba / Interfaz)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (34, 139, 34)
RED = (200, 0, 0)
BLUE = (0, 0, 255)

# ECONOMÍA INICIAL 
DINERO_INICIAL = 200
PUNTOS_INICIALES = 0

# COSTOS DE TORRES Y DEFENSAS 
COSTO_CIUDADANOS = 100
COSTO_GAUCHOS = 120
COSTO_GRANADEROS = 180

# COSTO DE TECNOLOGÍAS 
COSTO_HERRERIA = 150
COSTO_BARRICADAS = 200

# ESTADOS DEL JUEGO (PANTALLAS)
ESTADO_BIENVENIDA = "bienvenida"
ESTADO_MENU = "menu"
ESTADO_JUGAR_SELECCION = "seleccion_niveles"
ESTADO_GLOSARIO = "glosario"
ESTADO_CREDITOS = "creditos"
ESTADO_JUEGO_ACTIVO = "juego_activo"
ESTADO_GAME_OVER = "game_over"
ESTADO_FINAL_MISION = "final_mision"
ESTADO_ENDING = "ending"
